# http://docs.travis-ci.com/user/build-configuration/

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

sudo: false

install:
  - composer self-update
  - composer require 'satooshi/php-coveralls:0.7.*@dev'

before_script:
  - mysql --user=root -e "CREATE USER 'foo'@'localhost' IDENTIFIED BY 'foo';"
  - mysql --user=root -e "GRANT ALL PRIVILEGES ON *.* TO 'foo'@'localhost'"
  - mysql -e 'create database IF NOT EXISTS boxbilling'

script:
  - ant
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then src/bb-vendor/bin/phpunit --coverage-clover=build/logs/clover.xml tests/; fi;'

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then php vendor/bin/coveralls -v; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'

notifications:
  email: false
  slack: boxbilling:vsdKszFU9Pm308ye5rNSpr8n

before_deploy:
  - npm install -g grunt-cli
  - npm install
  - grunt
  - ant release
deploy:
  provider: releases
  api-key:
    secure: tVzZ+3U0ndBGvoUpFqA6ikg6fDKnPgMoNqK1pvTdEp0xmrFtjMP/fuc8+awObhj89iEC+MyzfsOP57CZbHR/UjmUSHPQew+BvTwxYmTUzgUeyUrYsTEI7WJgB7tsL35aRgrpxk102tlSmlX7EonufUT0svPOAQ1p4NgZRm3GI3A=
  file: ./build/distribution/BoxBilling.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    php: 5.3